stub in files from domain inventory sheet
18F/dns pull request #478
Opened 2020-10-06 06:11 UTC by afeld

Used the following script to create them, passing the CSV exported from [our domain list](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=824448842) as an argument:

```python
import csv
import os.path
import sys

source = sys.argv[1]
with open(source) as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        domain = row["Domain Name"].lower()
        if not domain:
            continue

        if row["Decommissioned"] == "TRUE":
            continue

        filename = f"{domain}.tf"
        if os.path.isfile(filename):
            continue

        print("Stubbing files…")
        print(domain)
        with open(filename, "w") as new_file:
            contents = """# managed by Corporate IT - request changes through
# https://gsa.servicenowservices.com/sp/?id=kb_article&sys_id=075cd185db26578058c2fd721f96193b
"""
            new_file.write(contents)
```

Did some manual checks and adjustment to make them accurate.

2020-10-06 06:12 UTC, afeld commented on terraform/citizenscience.gov.tf
> +challenge.gov.tf
This is a symlink.

2020-11-02 19:52 UTC, JJediny approved these changes
LGTM

2020-11-02 19:57 UTC, JJediny requested changes
@afeld just missed that the script and the reason for its use here should probably be added as content in the repo vs just in the PR comments (python script and when it may be needed in the future)

2020-11-02 22:17 UTC, afeld commented
I don't expect us to need the script again, hence not including it.

2020-11-03 16:15 UTC, JJediny approved these changes

2020-11-03 16:15 UTC, merged